### ISSUE TITLE
Some PPTs are broken (Nov 3, Dec 1)

### ISSUE THREAD

**Issue by retroinspect** [swtv-kaist/cs458-fall22#25]
It seems some ppt slides uploaded on the course webpage are broken .

Slides of Nov 3: [Verification of the multi-sector read of flash memory storage](https://swtv.kaist.ac.kr/courses/cs458-fall2022/part2-sw-model-checking/lec34-SMC-examples2.pptx)  have only partial contents.
Slides of Dec 1 (Makeup class 1): [Automated unit testing](https://swtv.kaist.ac.kr/courses/cs458-fall2022/concolic-testing/lec36.automated_unit_testing.pptx) have no content but only have templates.

**Comment by moonzoo** [comment]
> Slides of Nov 3: [Verification of the multi-sector read of flash memory storage](https://swtv.kaist.ac.kr/courses/cs458-fall2022/part2-sw-model-checking/lec34-SMC-examples2.pptx) have only partial contents.

The slides are correct (i.e., the slides contain only a short example of 5 pages)

> Slides of Dec 1 (Makeup class 1): [Automated unit testing](https://swtv.kaist.ac.kr/courses/cs458-fall2022/concolic-testing/lec36.automated_unit_testing.pptx) have no content but only have templates.

You can see the full content by closing a master slide view.

**Comment by retroinspect** [comment]
Thanks!
