### ISSUE TITLE
Concrete example of test oracle

### ISSUE THREAD

**Issue by retroinspect** [swtv-kaist/cs458-fall22#26]
1. I am not sure on what the test oracle is. Is it same as test driver? Is CROWN or CBMC itself test oracle? If not, Which entity(or code?) does play role of test oracle in CROWN/CBMC?

2. What does it mean by "test oracle plays critical role to reveal failure of a target program" from below slide?
If we have good set of test cases(in terms of rechability, infection, and propagation), we can just excecute them to <b>reveal</b> the failure, right? Why do we need another entity/software for revelation?

![image](https://user-images.githubusercontent.com/48230029/206639325-5c6f25a8-0ab7-4fc3-8b94-4ce5a1c23672.png)

**Comment by moonzoo** [comment]
> I am not sure on what the test oracle is. Is it same as test driver? 

No. Test oracles are different from test drivers.  

> Which entity(or code?) does play role of test oracle in CROWN/CBMC?

Assert statements are test oracles.

> If we have good set of test cases(in terms of rechability, infection, and propagation), we can just excecute them to reveal the failure, right?

Some people consider that testcases include test oracles, some other people do not.
So, I explicitly put emphasis on the importance of test oracles in testing.

**Comment by retroinspect** [comment]
Thanks!
