### ISSUE TITLE
Question on example of OneNAND Flash memory with CBMC

### ISSUE THREAD

**Issue by retroinspect** [swtv-kaist/cs458-fall22#27]
1. What does it mean by alphabet(ABCDEFG) from below image?
![image](https://user-images.githubusercontent.com/48230029/206652782-5344d562-cf9b-4543-be47-9e4a789747ef.png)

2. Why does combination of physical - logial map compute into 20^4?
With allowing a physical sector to be mapped into multiple logical sectors:
Each cell of leftmost table (from above image) can have 0/1/.../(max physical sector index)-1 and **no value**.
I think it should be ( 5(=number of physical unit)  * 4(=number of sector/unit)  ) ^ 5 (=number of sector/unit + 1).

With restriction of physical sector maps into at most one logical sector:
5(=number of physical unit) * 4(=number of sector/unit) Combination 4 (=number of sector/unit)
=> `(20*19*18*17) / (4*3*2*1)`

**Comment by moonzoo** [comment]
> What does it mean by alphabet(ABCDEFG) from below image?

The image shows the 2 different distributions of data "ABCDEFG" (fig a), (fig b) on physical NAND memory where each sector can contain only 1 character.

> Why does combination of physical - logial map compute into 20^4?

Exact # of possible distribution of l (<= 8) characters over n physical units is as follows: (see slide 17 of Nov 1st lecture slides)
![image](https://user-images.githubusercontent.com/55888021/206684395-76dfdda4-f20c-4bc8-8e0e-2da329a868e4.png)

**Comment by retroinspect** [comment]
> > What does it mean by alphabet(ABCDEFG) from below image?
> 
> The image shows the 2 different distributions of data "ABCDEFG" (fig a), (fig b) on physical NAND memory where each sector can contain only 1 character.

Thank you for kind response.
I wonder the distribution of ABCDEF with given SAMs (like leftmost table) are deterministic.
I think leftmost table only specifies where data should be in, but not fixes which data is in where.

**Comment by moonzoo** [comment]
> I think leftmost table only specifies where data should be in.

Yes, you are right.
