### ISSUE TITLE
[HW5-4] Measuring memory usage with top?

### ISSUE THREAD

**Issue by retroinspect** [swtv-kaist/cs458-fall22#8]
I wonder what is it mean by measuring memory usage with top.

`top` shows instant virtual memory usage and memory usage rate, but it soonly disappears as the process(cbmc) terminates.

I tried to utilize other softwares such as valgrind, but it seems not possible to setup the tools without sudo permission.

**Comment by ahcheongL** [comment]
You can try `grep ^VmPeak /proc/<process id>/status `

**Comment by moonzoo** [comment]
Or you can try `top -d 0.1| grep cbmc > mem_usage.txt` where `-d N` indicates update frequency in second.
